QlikAuthentication/Controllers/QlikSessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QlikAuthentication.Models;
using QlikAuthentication.QlikAuthentication;
using System.Web.SessionState;

namespace QlikAuthentication.Controllers
{
    public class QlikSessionController : Controller
    {
        public ActionResult Index()
        {
            QlikSessionViewModel model = new QlikSessionViewModel
            {
                Server = "https://172.19.13.100",
                Port = "4243",
                Certificate = "QlikClient",
                VirtualProxy = "detectr",
                UserDirectory = "MITRAIS",
                User = "agungb_d"
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult RequestSession(QlikSessionViewModel model)
        {
            Authentication auth = new Authentication(model.Server, model.VirtualProxy, model.Port, model.Certificate, model.UserDirectory, model.User, model.SessionId);

            try
            {
                SessionResponse response = auth.GetSession();

                DateTime now = DateTime.Now;
                HttpCookie cookie = new HttpCookie(string.Format("X-Qlik-Session{0}", string.IsNullOrEmpty(model.VirtualProxy) ? string.Empty : "-" + model.VirtualProxy));
                cookie.Value = response.SessionId;
                cookie.Expires = DateTime.MinValue;
                cookie.HttpOnly = true;

                cookie.Domain = model.Server; // only works if qliksense url domain is same with this web app

                Request.Cookies.Add(cookie);
                Response.Cookies.Add(cookie);

                return Json(string.Format("{0}{1}/qmc", model.Server, string.IsNullOrEmpty(model.VirtualProxy) ? string.Empty : "/" + model.VirtualProxy));
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public ActionResult GetSession()
        {
            SessionIDManager manager = new SessionIDManager();
            string sessionId = manager.CreateSessionID(System.Web.HttpContext.Current);
            bool redirected = false;
            bool isAdded = false;
            manager.SaveSessionID(System.Web.HttpContext.Current, sessionId, out redirected, out isAdded);
            return Json(sessionId);
        }
    }
}

QlikAuthentication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="loading-screen">
        <div class="center-div">
            <div class="inner-div">
                <div class="loader"></div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Qlik Authentication", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Qlik Ticket", "Index", "Home")</li>
                    <li>@Html.ActionLink("Qlik Session", "Index", "QlikSession")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>    

    <script type="text/javascript">
        var homeUrl = '@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))';
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>